// config.js
export const AIRTABLE_API_KEY = process.env.NEXT_PUBLIC_AIRTABLE_API_KEY;
export const AIRTABLE_BASE_ID = process.env.NEXT_PUBLIC_AIRTABLE_BASE_ID;
export const WHATSAPP_ID_INSTANCE = process.env.NEXT_PUBLIC_WHATSAPP_ID_INSTANCE;
export const WHATSAPP_API_TOKEN_INSTANCE = process.env.NEXT_PUBLIC_WHATSAPP_API_TOKEN_INSTANCE;